# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' testPackage
#' 
#' Test the linear regression implemented in the package
#' @return nothing
testPackage <- function() {
    invisible(.Call(`_lesstimateTemplateR_testPackage`))
}

