name: check cpp documentation

on:
  push:
    branches: [ "main"]

permissions:
  contents: read

jobs:
 build:
  runs-on: ubuntu-latest
    
  steps:
    - uses: actions/checkout@v3
      with:
       submodules: 'true'
    - uses: r-lib/actions/setup-r@v2
    - name: install dependencies
      run: |
        install.packages(c("devtools", "RcppAramdillo"))
      shell: Rscript {0}
    - name: install package
      run: |
        devtools::install(pkg = ".")
      shell: Rscript {0}
    - name: run test
      run: |
        library("lessparTemplateR")
        testPackage()
      shell: Rscript {0}
      
